# Generated by Django 6.0.3 on 2026-03-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='speeches/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('speech_speed', models.FloatField(default=0.0)),
                ('filler_word_count', models.IntegerField(default=0)),
                ('pause_count', models.IntegerField(default=0)),
                ('voice_stability', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
